---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-issue-core-github-io-v1-githubissue
  failurePolicy: Fail
  name: mgithubissue.kb.io
  rules:
  - apiGroups:
    - issue.core.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubissues
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-issue-core-github-io-v1-githubissue
  failurePolicy: Fail
  name: vgithubissue.kb.io
  rules:
  - apiGroups:
    - issue.core.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - githubissues
  sideEffects: None
